# Generated by Django on 2025-08-10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellapp', '0002_client_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('totals', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
