# Generated by Django 5.2.5 on 2025-08-10 20:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellapp', '0003_nightaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('suite', 'Suite'), ('apartment', 'Serviced Apartment'), ('junior_suite', 'Junior Suite')], max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='hotellapp.room')),
            ],
            options={
                'verbose_name': 'Rate season',
                'verbose_name_plural': 'Rate seasons',
                'ordering': ['start_date'],
            },
        ),
    ]
