# Generated by Django 5.2.5 on 2025-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotellapp', '0004_rateseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateseason',
            name='apply_on',
            field=models.CharField(choices=[('all', 'All days'), ('weekdays', 'Weekdays (Mon–Fri)'), ('weekends', 'Weekends (Sat–Sun)')], default='all', max_length=10),
        ),
    ]
